micronaut:
  application:
    name: mnFirebaseTenantProviders
---
logger:
  levels:
    mn.firebase: DEBUG
---
gcp:
  project-id: 'your-project-id'
  credentials:
    location: /path/to/your/credentials.json
